In [1]:
import numpy as np
import pandas as pd

# q_01

In [2]:
np.__version__

'1.21.5'

# q_02

In [3]:
df = pd.read_csv('data.csv')

In [4]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [5]:
df.shape

(11914, 16)

# q_03

In [6]:
df['Make'].value_counts().head(3)

Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64

# q_04

In [7]:
df[df['Make'] == 'Audi']['Model'].nunique()

34

# q_05

In [8]:
df.isna().mean() > 0

Make                 False
Model                False
Year                 False
Engine Fuel Type      True
Engine HP             True
Engine Cylinders      True
Transmission Type    False
Driven_Wheels        False
Number of Doors       True
Market Category       True
Vehicle Size         False
Vehicle Style        False
highway MPG          False
city mpg             False
Popularity           False
MSRP                 False
dtype: bool

# q_06

In [9]:
df['Engine Cylinders'].median()

6.0

In [10]:
eng_cyl_pop_val = df['Engine Cylinders'].value_counts().head(5)
eng_cyl_pop_val

4.0     4752
6.0     4489
8.0     2031
12.0     230
5.0      225
Name: Engine Cylinders, dtype: int64

In [11]:
df_copy = df.copy()

In [12]:
df_copy['Engine Cylinders'] = df_copy['Engine Cylinders'].fillna(4.0)

In [13]:
df_copy['Engine Cylinders'].median()

6.0

In [14]:
df_copy['Engine Cylinders'].isna().sum()

0

# q_07

In [15]:
df_lotus = df[df['Make'] == 'Lotus'].reset_index()

In [16]:
df_lotus.head()

index   Make  Model  Year             Engine Fuel Type  Engine HP  \
0   3912  Lotus  Elise  2009  premium unleaded (required)      189.0   
1   3913  Lotus  Elise  2009  premium unleaded (required)      218.0   
2   3914  Lotus  Elise  2009  premium unleaded (required)      189.0   
3   3915  Lotus  Elise  2010  premium unleaded (required)      189.0   
4   3916  Lotus  Elise  2010  premium unleaded (required)      218.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               4.0            MANUAL  rear wheel drive              2.0   
1               4.0            MANUAL  rear wheel drive              2.0   
2               4.0            MANUAL  rear wheel drive              2.0   
3               4.0            MANUAL  rear wheel drive              2.0   
4               4.0            MANUAL  rear wheel drive              2.0   

           Market Category Vehicle Size Vehicle Style  highway MPG  city mpg  \
0  Exotic,High-Performance      Compact   Convertible           27        21   
1  Exotic,High-Performance      Compact   Convertible           26        20   
2  Exotic,High-Performance      Compact   Convertible           27        21   
3  Exotic,High-Performance      Compact   Convertible           27        21   
4  Exotic,High-Performance      Compact   Convertible           26        20   

   Popularity   MSRP  
0         613  43995  
1         613  54990  
2         613  47250  
3         613  47250  
4         613  54990

In [17]:
df_lotus_cut = df_lotus[['Engine HP', 'Engine Cylinders']]

In [18]:
df_lotus_cut.shape

(29, 2)

In [19]:
df_lotus_cut = df_lotus_cut.drop_duplicates()

In [20]:
df_lotus_cut.shape

(9, 2)

In [21]:
x = df_lotus_cut.to_numpy()

In [22]:
x

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [23]:
np.matmul(x.T, x)

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [24]:
np.linalg.inv(np.matmul(x.T, x)).shape

(2, 2)

In [25]:
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])

In [26]:
np.matmul(np.matmul(np.linalg.inv(np.matmul(x.T, x)), x.T), y)

array([  4.59494481, -63.56432501])